# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a62eac6846b94798685f5b15088bf8743ea194831c9ee2606e5bac4b35a34b1a73d2d417543d6824619c3be3539e0cbafef83fb3003402d1670cc7272c90832

test:
  secret_key_base: f2707dbfb757171d0a4a938465eeb99f9237402a437d7cbbc20cf70e1dc65b6039227d0e8a32e81f41de74a28825faf46e4614f2c652630afdfb155068f319fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
